/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VeiculoCarIdRouteImport } from './routes/veiculo.$carId'
import { Route as AdminVeiculosRouteImport } from './routes/admin.veiculos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'

const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VeiculoCarIdRoute = VeiculoCarIdRouteImport.update({
  id: '/veiculo/$carId',
  path: '/veiculo/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVeiculosRoute = AdminVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/estoque': typeof EstoqueRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/veiculo/$carId': typeof VeiculoCarIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estoque': typeof EstoqueRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/veiculo/$carId': typeof VeiculoCarIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/estoque': typeof EstoqueRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/veiculo/$carId': typeof VeiculoCarIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/estoque'
    | '/admin/insights'
    | '/admin/login'
    | '/admin/veiculos'
    | '/veiculo/$carId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estoque'
    | '/admin/insights'
    | '/admin/login'
    | '/admin/veiculos'
    | '/veiculo/$carId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/estoque'
    | '/admin/insights'
    | '/admin/login'
    | '/admin/veiculos'
    | '/veiculo/$carId'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EstoqueRoute: typeof EstoqueRoute
  VeiculoCarIdRoute: typeof VeiculoCarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/veiculo/$carId': {
      id: '/veiculo/$carId'
      path: '/veiculo/$carId'
      fullPath: '/veiculo/$carId'
      preLoaderRoute: typeof VeiculoCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/veiculos': {
      id: '/admin/veiculos'
      path: '/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AdminVeiculosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminVeiculosRoute: typeof AdminVeiculosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInsightsRoute: AdminInsightsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminVeiculosRoute: AdminVeiculosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EstoqueRoute: EstoqueRoute,
  VeiculoCarIdRoute: VeiculoCarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
