/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VeiculoCarIdRouteImport } from './routes/veiculo.$carId'
import { Route as AdminVeiculosRouteImport } from './routes/admin.veiculos'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInsightsRouteImport } from './routes/admin.insights'
import { Route as AdminFinanceiroRouteImport } from './routes/admin.financeiro'
import { Route as AdminCrmRouteImport } from './routes/admin.crm'
import { Route as AdminCrmLeadsRouteImport } from './routes/admin.crm.leads'
import { Route as AdminCrmFunilRouteImport } from './routes/admin.crm.funil'
import { Route as AdminCrmFinanceiroRouteImport } from './routes/admin.crm.financeiro'
import { Route as AdminCrmLeadLeadIdRouteImport } from './routes/admin.crm.lead.$leadId'

const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VeiculoCarIdRoute = VeiculoCarIdRouteImport.update({
  id: '/veiculo/$carId',
  path: '/veiculo/$carId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVeiculosRoute = AdminVeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInsightsRoute = AdminInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmLeadsRoute = AdminCrmLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminCrmRoute,
} as any)
const AdminCrmFunilRoute = AdminCrmFunilRouteImport.update({
  id: '/funil',
  path: '/funil',
  getParentRoute: () => AdminCrmRoute,
} as any)
const AdminCrmFinanceiroRoute = AdminCrmFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminCrmRoute,
} as any)
const AdminCrmLeadLeadIdRoute = AdminCrmLeadLeadIdRouteImport.update({
  id: '/lead/$leadId',
  path: '/lead/$leadId',
  getParentRoute: () => AdminCrmRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/estoque': typeof EstoqueRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/veiculo/$carId': typeof VeiculoCarIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/crm/financeiro': typeof AdminCrmFinanceiroRoute
  '/admin/crm/funil': typeof AdminCrmFunilRoute
  '/admin/crm/leads': typeof AdminCrmLeadsRoute
  '/admin/crm/lead/$leadId': typeof AdminCrmLeadLeadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estoque': typeof EstoqueRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/veiculo/$carId': typeof VeiculoCarIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/crm/financeiro': typeof AdminCrmFinanceiroRoute
  '/admin/crm/funil': typeof AdminCrmFunilRoute
  '/admin/crm/leads': typeof AdminCrmLeadsRoute
  '/admin/crm/lead/$leadId': typeof AdminCrmLeadLeadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/estoque': typeof EstoqueRoute
  '/admin/crm': typeof AdminCrmRouteWithChildren
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/insights': typeof AdminInsightsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/veiculos': typeof AdminVeiculosRoute
  '/veiculo/$carId': typeof VeiculoCarIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/crm/financeiro': typeof AdminCrmFinanceiroRoute
  '/admin/crm/funil': typeof AdminCrmFunilRoute
  '/admin/crm/leads': typeof AdminCrmLeadsRoute
  '/admin/crm/lead/$leadId': typeof AdminCrmLeadLeadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/estoque'
    | '/admin/crm'
    | '/admin/financeiro'
    | '/admin/insights'
    | '/admin/login'
    | '/admin/veiculos'
    | '/veiculo/$carId'
    | '/admin/'
    | '/admin/crm/financeiro'
    | '/admin/crm/funil'
    | '/admin/crm/leads'
    | '/admin/crm/lead/$leadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estoque'
    | '/admin/crm'
    | '/admin/financeiro'
    | '/admin/insights'
    | '/admin/login'
    | '/admin/veiculos'
    | '/veiculo/$carId'
    | '/admin'
    | '/admin/crm/financeiro'
    | '/admin/crm/funil'
    | '/admin/crm/leads'
    | '/admin/crm/lead/$leadId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/estoque'
    | '/admin/crm'
    | '/admin/financeiro'
    | '/admin/insights'
    | '/admin/login'
    | '/admin/veiculos'
    | '/veiculo/$carId'
    | '/admin/'
    | '/admin/crm/financeiro'
    | '/admin/crm/funil'
    | '/admin/crm/leads'
    | '/admin/crm/lead/$leadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  EstoqueRoute: typeof EstoqueRoute
  VeiculoCarIdRoute: typeof VeiculoCarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/veiculo/$carId': {
      id: '/veiculo/$carId'
      path: '/veiculo/$carId'
      fullPath: '/veiculo/$carId'
      preLoaderRoute: typeof VeiculoCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/veiculos': {
      id: '/admin/veiculos'
      path: '/veiculos'
      fullPath: '/admin/veiculos'
      preLoaderRoute: typeof AdminVeiculosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/insights': {
      id: '/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AdminInsightsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm/leads': {
      id: '/admin/crm/leads'
      path: '/leads'
      fullPath: '/admin/crm/leads'
      preLoaderRoute: typeof AdminCrmLeadsRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin/crm/funil': {
      id: '/admin/crm/funil'
      path: '/funil'
      fullPath: '/admin/crm/funil'
      preLoaderRoute: typeof AdminCrmFunilRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin/crm/financeiro': {
      id: '/admin/crm/financeiro'
      path: '/financeiro'
      fullPath: '/admin/crm/financeiro'
      preLoaderRoute: typeof AdminCrmFinanceiroRouteImport
      parentRoute: typeof AdminCrmRoute
    }
    '/admin/crm/lead/$leadId': {
      id: '/admin/crm/lead/$leadId'
      path: '/lead/$leadId'
      fullPath: '/admin/crm/lead/$leadId'
      preLoaderRoute: typeof AdminCrmLeadLeadIdRouteImport
      parentRoute: typeof AdminCrmRoute
    }
  }
}

interface AdminCrmRouteChildren {
  AdminCrmFinanceiroRoute: typeof AdminCrmFinanceiroRoute
  AdminCrmFunilRoute: typeof AdminCrmFunilRoute
  AdminCrmLeadsRoute: typeof AdminCrmLeadsRoute
  AdminCrmLeadLeadIdRoute: typeof AdminCrmLeadLeadIdRoute
}

const AdminCrmRouteChildren: AdminCrmRouteChildren = {
  AdminCrmFinanceiroRoute: AdminCrmFinanceiroRoute,
  AdminCrmFunilRoute: AdminCrmFunilRoute,
  AdminCrmLeadsRoute: AdminCrmLeadsRoute,
  AdminCrmLeadLeadIdRoute: AdminCrmLeadLeadIdRoute,
}

const AdminCrmRouteWithChildren = AdminCrmRoute._addFileChildren(
  AdminCrmRouteChildren,
)

interface AdminRouteChildren {
  AdminCrmRoute: typeof AdminCrmRouteWithChildren
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminInsightsRoute: typeof AdminInsightsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminVeiculosRoute: typeof AdminVeiculosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCrmRoute: AdminCrmRouteWithChildren,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminInsightsRoute: AdminInsightsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminVeiculosRoute: AdminVeiculosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  EstoqueRoute: EstoqueRoute,
  VeiculoCarIdRoute: VeiculoCarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
